name: Run Soul 50x

on:
  push:
  schedule:
    - cron: '0 * * * *'
jobs:
  soul:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        n: [1,2,3,4,5,6,7,8,9,10]
    steps:
      - uses: actions/checkout@v3
      - name: Make binary executable
        run: chmod +x soul && pip install paramiko
      - name: Run soul1 binary
        run: python3 Soul.py

